---
title: "Reproducible research and data science"
author: "Julian"
date: "June 16, 2015"
output: 
  beamer_presentation: 
    colortheme: dolphin
    keep_tex: yes
    theme: Frankfurt
---

# Importance of reproducible research
- Basic reports/summaries
- Consistent mistakes
- Replicating results

# Application of reproducible research
- Funding  
    + Figuring out dead ends  
    + Agencies/foundations require audits  
* Accessibility:  
    + Journals: raw data, analyses, figures  
    + Supplemental data  
    + Public resource  
* Fraud detection
    + Benford's law/distribution  
    + [Irregularities in LaCour 2014](http://stanford.edu/~dbroock/broockman_kalla_aronow_lg_irregularities.pdf)  
  
# 'Practical' applications of reproducible research
- Job applications
- Tutorials
- Demonstrating skills
- Showcasing projects
- Publishing/portfolio

# Resources
- LaTex: wonderful, sharp learning curve
* R + RStudio  
    + Sweave: can use LaTex + R, Python, etc.  
    + knitr: (R) Markdown + R code, Python, etc.  
* Python
    + Jupyter/IPython: Markdown + Python/IPython + 'magics'  
    + Eclipse  
* Git/GitHub  
    + Sharing data publicly
    + Tracking changes/version control  
    + Portfolio/public persona